
name: GitHub Actions Demo
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -run: echo " The job was automatically triggeredby a ${{ github.event_name}} event."
      -run: python main.py